packages:
  - 'apps/**'
  - 'packages/*'
  - 'configs/*'
catalogs:
  dev:
    '@antfu/eslint-config': ^4.10.1
    '@commitlint/cli': ^19.6.1
    '@commitlint/config-conventional': ^19.6.0
    '@eslint-react/eslint-plugin': ^1.23.2
    '@eslint/eslintrc': ^3.3.0
    '@eslint/js': ^9.21.0
    '@iconify/json': ^2.2.322
    '@types/mockjs': ^1.0.10
    '@types/node': ^22.10.6
    '@types/nprogress': ^0.2.3
    '@types/qrcode': ^1.5.5
    '@types/react': ^19.0.10
    '@types/react-dom': ^19.0.4
    '@unocss/eslint-plugin': ^65.4.0
    '@unocss/nuxt': ^66.1.2
    '@unocss/preset-web-fonts': ^66.1.2
    '@unocss/reset': ^66.1.2
    '@vitejs/plugin-react': ^4.3.4
    '@vitejs/plugin-vue': ^5.2.1
    '@vitejs/plugin-vue-jsx': ^4.2.0
    '@vue/compiler-sfc': ^3.5.13
    '@vue/tsconfig': ^0.7.0
    '@vueup/vue-quill': ^1.2.0
    eslint: ^9.21.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.1.0
    eslint-plugin-react-refresh: ^0.4.19
    globals: ^15.15.0
    husky: ^9.1.7
    lint-staged: ^15.3.0
    mockjs: ^1.1.0
    prettier: ^3.2.5
    rollup-plugin-visualizer: ^5.9.0
    terser: ^5.39.2
    turbo: ^2.4.4
    typescript: ^5.7.3
    typescript-eslint: ^8.24.1
    unocss: 66.1.2
    unplugin-auto-import: ^19.1.1
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.4.1
    vite: ^6.2.0
    vite-plugin-compression: ^0.5.1
    vite-plugin-fake-server: ^2.2.0
    vite-plugin-mock: ^3.0.2
    vite-plugin-svg-icons: ^2.0.1
    vite-plugin-vue-devtools: ^7.7.6
    vue-tsc: ^2.2.8
  prod:
    '@better-scroll/core': ^2.5.1
    '@bytemd/plugin-gfm': ^1.22.0
    '@bytemd/vue-next': ^1.22.0
    '@iconify/vue': ^4.3.0
    '@visactor/vchart': ^1.13.10
    '@visactor/vchart-theme': ^1.12.2
    '@vueuse/core': ^13.0.0
    '@wangeditor/editor': ^5.1.23
    '@wangeditor/editor-for-vue': ^5.1.12
    antd: ^5.24.7
    axios: ^1.7.9
    bytemd: ^1.22.0
    dayjs: ^1.11.13
    echarts: ^5.6.0
    jsbarcode: ^3.11.6
    localforage: ^1.10.0
    naive-ui: ^2.41.0
    nprogress: ^0.2.0
    nuxt: ^3.15.4
    pinia: ^3.0.0
    qrcode: ^1.5.4
    react: ^19.0.0
    react-dom: ^19.0.0
    react-router-dom: ^7.5.0
    vue: ^3.5.13
    vue-i18n: ^11.1.2
    vue-router: ^4.5.0
    zustand: ^5.0.3
