packages:
  - 'apps/**'
  - 'packages/*'
  - 'configs/*'
catalogs:
  dev:
    '@antfu/eslint-config': ^4.10.1
    '@commitlint/cli': ^19.6.1
    '@commitlint/config-conventional': ^19.6.0
    '@eslint-react/eslint-plugin': ^1.23.2
    '@eslint/eslintrc': ^3.3.0
    '@eslint/js': ^9.21.0
    '@iconify/json': ^2.2.322
    '@nestjs/cli': ^11.0.0
    '@nestjs/schematics': ^11.0.0
    '@nestjs/testing': ^11.0.1
    '@svgr/core': ^8.1.0
    '@svgr/plugin-jsx': ^8.1.0
    '@types/express': ^5.0.0
    '@types/jest': ^30.0.0
    '@types/mockjs': ^1.0.10
    '@types/node': ^22.10.6
    '@types/nprogress': ^0.2.3
    '@types/qrcode': ^1.5.5
    '@types/react': ^19.0.10
    '@types/react-dom': ^19.0.4
    '@types/react-syntax-highlighter': ^15.5.13
    '@types/splitpanes': ^2.2.6
    '@types/supertest': ^6.0.2
    '@unocss/eslint-plugin': ^66.5.0
    '@unocss/nuxt': ^66.5.0
    '@unocss/preset-web-fonts': ^66.5.0
    '@unocss/reset': ^66.5.0
    '@vitejs/plugin-react': ^4.3.4
    '@vitejs/plugin-vue': ^5.2.1
    '@vitejs/plugin-vue-jsx': ^4.2.0
    '@vue/compiler-sfc': ^3.5.13
    '@vue/tsconfig': ^0.7.0
    eslint: ^9.21.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-prettier: ^5.2.2
    eslint-plugin-react-hooks: ^5.1.0
    eslint-plugin-react-refresh: ^0.4.19
    globals: ^15.15.0
    husky: ^9.1.7
    jest: ^30.0.0
    lint-staged: ^15.3.0
    mockjs: ^1.1.0
    prettier: ^3.2.5
    rollup-plugin-visualizer: ^5.9.0
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    terser: ^5.39.2
    ts-jest: ^29.2.5
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    turbo: ^2.4.4
    typescript: ^5.7.3
    typescript-eslint: ^8.24.1
    unocss: ^66.5.0
    unplugin-auto-import: ^19.1.1
    unplugin-auto-import-antd: ^0.0.2
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.4.1
    vite: ^6.2.0
    vite-plugin-compression: ^0.5.1
    vite-plugin-dynamic-import: ^1.6.0
    vite-plugin-fake-server: ^2.2.0
    vite-plugin-imagemin: ^0.6.1
    vite-plugin-mock: ^3.0.2
    vite-plugin-svg-icons: ^2.0.1
    vite-plugin-vue-devtools: ^7.7.6
    vue-tsc: ^2.2.8
  prod:
    '@better-scroll/core': ^2.5.1
    '@bytemd/plugin-gfm': ^1.22.0
    '@bytemd/vue-next': ^1.22.0
    '@codemirror/lang-json': ^6.0.2
    '@codemirror/lint': ^6.8.5
    '@hookform/resolvers': ^5.2.1
    '@iconify/react': ^6.0.0
    '@iconify/vue': ^4.3.0
    '@nestjs/common': ^11.0.1
    '@nestjs/core': ^11.0.1
    '@nestjs/platform-express': ^11.0.1
    '@reduxjs/toolkit': ^2.8.2
    '@uiw/codemirror-extensions-langs': ^4.25.1
    '@uiw/codemirror-themes-all': ^4.25.1
    '@uiw/react-codemirror': ^4.25.1
    '@visactor/vchart': ^1.13.10
    '@visactor/vchart-theme': ^1.12.2
    '@viz-js/lang-dot': ^1.0.5
    '@vueup/vue-quill': ^1.2.0
    '@vueuse/core': ^13.0.0
    '@wangeditor/editor': ^5.1.23
    '@wangeditor/editor-for-react': ^1.0.6
    '@wangeditor/editor-for-vue': ^5.1.12
    ahooks: ^3.9.0
    antd: ^5.24.7
    axios: ^1.7.9
    bytemd: ^1.22.0
    classnames: ^2.5.1
    clsx: ^2.1.1
    codemirror-lang-mermaid: ^0.5.0
    colord: ^2.9.3
    dayjs: ^1.11.13
    echarts: ^5.6.0
    emoji-picker-react: ^4.13.2
    github-markdown-css: ^5.8.1
    i18next: ^25.3.1
    i18next-browser-languagedetector: ^8.2.0
    i18next-http-backend: ^3.0.2
    js-calendar-converter: ^0.0.7
    jsbarcode: ^3.11.6
    katex: ^0.16.22
    localforage: ^1.10.0
    lunar-typescript: ^1.8.0
    motion: ^12.23.15
    naive-ui: ^2.41.0
    nprogress: ^0.2.0
    nuxt: ^3.15.4
    pinia: ^3.0.0
    qrcode: ^1.5.4
    qrcode.react: ^4.2.0
    query-string: ^9.2.2
    react: ^19.0.0
    react-dom: ^19.0.0
    react-hook-form: ^7.61.1
    react-i18next: ^15.6.0
    react-markdown: ^10.1.0
    react-redux: ^9.2.0
    react-responsive: ^10.0.1
    react-router-dom: ^7.5.0
    react-syntax-highlighter: ^15.6.3
    reflect-metadata: ^0.2.2
    rehype-katex: ^7.0.1
    rehype-raw: ^7.0.0
    remark-cjk-friendly: ^1.2.0
    remark-gfm: ^4.0.1
    remark-math: ^6.0.0
    rxjs: ^7.8.1
    seemly: ^0.3.10
    simplebar-react: ^3.3.2
    splitpanes: ^4.0.4
    styled-components: ^6.1.19
    vue: ^3.5.13
    vue-i18n: ^11.1.2
    vue-router: ^4.5.0
    vue3-count-to: ^1.1.2
    vue3-emoji-picker: ^1.1.8
    zod: ^4.0.14
    zustand: ^5.0.3
